# Generated by Django 6.0.3 on 2026-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
